#!/usr/bin/env bash
# Displays 'Best School' 10 times with while and if, hi on 9th iteration
index=0
while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
done
